
CREATE TABLE Pessoa (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
	Endereco VARCHAR(150) NOT NULL,
	Cep VARCHAR(7) NOT NULL,
	TelefoneCelular VARCHAR(13) NOT NULL,
	TelefoneResidencial VARCHAR(13) NULL,
	Email VARCHAR(150) NOT NULL,
	Sexo CHAR(1) NOT NULL,
	Observacoes TEXT,
    DataCadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
